queue: 
  name: Developer

trigger:
- master
- releases/*

steps:
- task: dotNetCoreCLI@2
  inputs:
    command: restore
    projects: "src/**/*.csproj"
  displayName: dotnet restore

- task: dotNetCoreCLI@2
  inputs:
    command: build
    projects: "src/**/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

# - task: dotNetCoreCLI@1
#   inputs:
#     command: test 
#     projects: "**/*Tests/*.csproj"
#     arguments: --configuration release
#   displayName: dotnet build

- task: dotNetCoreCLI@2
  inputs:
    command: publish    
    publishWebProjects: false
    projects: "src/**/*.csproj"
    arguments: --configuration release --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
  displayName: dotnet publish

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
  displayName: Publish the artifacts